
name: Node.js CI

on:
  push:
    branches:
      - final_project
  pull_request:
    branches:
      - final_project

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: |
          cd server
          npm install
          npm ci
      - name: Build
        run: |
          cd server
          npm run build --if-present
      - name: Test
        run: |
          cd server
          npm start &
          npm test
